name: hmbc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #图像缓存
  cached_network_image: ^0.8.0 
  #日期
  flutter_picker: ^1.0.13
  #html
  flutter_html: ^0.9.8
  #webview
  webview_flutter: ^0.3.19+9
  #toast
  fluttertoast: ^3.1.0
# 本地存储、收藏功能
  #shared_preferences: ^0.4.3
#相机相册
  image_picker: ^0.6.0+15
#分享
  share: ^0.6.3+6
dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/01.png
    - asset/images/02.png
    - asset/images/03.png
    - asset/images/04.png
    - asset/images/head.png
    - asset/images/idfront.png
    - asset/images/idback.png
    - asset/images/topBanner.jpg
    #病历图片
    - asset/images/bl_07.jpg
    - asset/images/bl_03.jpg
    - asset/images/blxq_03.jpg
    - asset/images/blxq_05.jpg
    - asset/images/blxq_07.jpg
    - asset/images/crop.png
    #
    - asset/images/bg_02.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
